
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import AuthProvider from "@/components/authProvider";
import Cursor from "@/components/CustomCursor";
import "./globals.css"


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CESA-CSI VPPCOE-VA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className={inter.className}>
        <Cursor />
          <Toaster position="top-center" reverseOrder={false} />
            <AuthProvider>{children}</AuthProvider>

        </div>
      </body>
    </html>
  );
}
